import Navigation from '../components/Navigation'
import Footer from '../components/Footer'
import './global.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navigation/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
